% Agent Options
agentOpts = rlDQNAgentOptions(...
    'UseDoubleDQN', false, ...    
    'TargetUpdateMethod', "smoothing", ...
    'TargetSmoothFactor', 1e-3, ... 
    'ExperienceBufferLength',1e6,... 
    'DiscountFactor', 0.99, ... % the discount factor determines the tradeoff between short-term and long-term rewards
    'SampleTime',env.Ts, ...
    'MiniBatchSize', 64);
agentOpts.EpsilonGreedyExploration.EpsilonDecay = 1e-5;

% Training Options
trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 5000, ...
    'MaxStepsPerEpisode', 500, ...
    'Verbose', true, ...
    'Plots','training-progress',...
    'StopTrainingCriteria' ,'AverageReward',...
    'SaveAgentCriteria','EpisodeReward',...
    'SaveAgentValue',-2000,...
    'StopTrainingValue',-1000);